/**
 * @file index.ts
 * @description  Interface
 * @copyright Copyright (c) 2025 Arun Gopi
 * @author Arun Gopi 
 * @date 2025-07-14
 * @module core/ports
 *
 */

/**
 * IRepository Interface
 *
 * A generic interface for defining basic CRUD (Create, Read, Update, Delete)
 * operations for any entity. This promotes a consistent API for data access
 * across different parts of your application and abstracts away the
 * underlying database technology (e.g., Prisma, TypeORM, raw SQL).
 *
 * @template T The type of the entity (e.g., User, Product, TaggedDataset).
 * @template ID The type of the entity's primary key (e.g., number, string).
 */
export interface IRepository<T, ID> {
  /**
   * Finds an entity by its unique identifier.
   * @param id The ID of the entity to find.
   * @returns A Promise that resolves to the entity if found, otherwise null.
   */
  findById(id: ID): Promise<T | null>;

  /**
   * Finds all entities. In a real-world application, this would often
   * include pagination, filtering, and sorting parameters.
   * @returns A Promise that resolves to an array of entities.
   */
  findAll(): Promise<T[]>;

  /**
   * Creates a new entity.
   * @param entityData The data for the new entity. Use `Omit<T, 'id'>` or `Partial<T>`
   * if the ID is auto-generated by the database.
   * @returns A Promise that resolves to the created entity.
   */
  create(entityData: Omit<T, 'id'>): Promise<T>; // Omit 'id' as it's often auto-generated

  /**
   * Updates an existing entity by its ID.
   * @param id The ID of the entity to update.
   * @param updateData The data to update the entity with. `Partial<T>` allows for
   * updating only specific fields.
   * @returns A Promise that resolves to the updated entity if found, otherwise null.
   */
  update(id: ID, updateData: Partial<T>): Promise<T | null>;

  /**
   * Deletes an entity by its unique identifier.
   * @param id The ID of the entity to delete.
   * @returns A Promise that resolves when the entity is deleted.
   * (Could also return the deleted entity or a boolean indicating success).
   */
  delete(id: ID): Promise<T>;

  // You can add more specific methods here as needed, e.g.:
  // findByCriteria(criteria: any): Promise<T[]>;
  // count(criteria?: any): Promise<number>;
}